data_raw = {}
data_raw['1'] = "science of intelligence
principles, exploration, exploitation, complexity, reduction, decision making,
time, processes, 
interaction, environmental, social,
theory of mind,
heuristics, nice strategies,
anticipation, prediction,
flow, intrinsic motivation,
diversity, variability,
closed-loop learning,
introspection, reflectivity, cognition,
pillars, metabolism, reproduction,
evolution, population, diversity, heredity, selection,
deductive, mathematical, biology,
social life of electrons,
decomposition,
intelligence,
open-ended learning,
short-term, consolidation, memory,
21st century,
evolutionary robotics, developmental robotics,
psychology, neuroscience, machine learning, optimization,
control theory, reinforcement learning, cybernetics,
embodiment, exploration, self-exploration, black-box optimization,
representation learning, relational learning, error-based learning,
the reward prediction hypothesis of dopamine, exploitation,
stochastic gradient descent, self-organization, learning rules,
correlational learning, measures, data,
tappings,
internal models, developmental models,
environment, agents, predictive coding,"
